// Once the images have been generated, execute this script.
// Ex. $ node generate-pdf.js

const numberOfImages = 493; // Number of images generated by generate-images.js

PDFDocument = require('pdfkit');
fs = require('fs');
doc = new PDFDocument;

//Pipe its output somewhere, like to a file or HTTP response 
//See below for browser usage 
doc.pipe(fs.createWriteStream('output.pdf'));

//Add an image, constrain it to a given size, and center it vertically and horizontally 
doc.image('./images/0.png', {
   fit: [800, 600],
   //align: 'center',
   //valign: 'center'
});

for (let i = 1; i <= numberOfImages; i++) {
   doc.addPage()
      .image('./images/' + i + '.png', {
      fit: [800, 600],
      //align: 'center',
      //valign: 'center'
   });
}

doc.end();
